on:
  - push
  - workflow_dispatch
jobs:
  lint:
    uses: ashep/ci/.github/workflows/go-lint.yaml@v1

  test:
    needs:
      - lint
    uses: ashep/ci/.github/workflows/go-test.yaml@v1

  build:
    needs:
      - test
    uses: ashep/ci/.github/workflows/go-build.yaml@v1
    with:
      registry_user: ${{ vars.REGISTRY_USER }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  deploy:
    uses: ashep/ci/.github/workflows/deploy-docker.yaml@v1
    needs:
      - build
    secrets:
      ssh_host: ${{ secrets.DEPLOY_SSH_HOST }}
      ssh_port: ${{ secrets.DEPLOY_SSH_PORT }}
      ssh_user: ${{ secrets.DEPLOY_SSH_USER }}
      ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
      dotenv: |
        APP_PROXY_URLS=${{ vars.APP_PROXY_URLS }}
        APP_SKIP_TODAY=1
        APP_TG_TOKEN=${{ secrets.APP_TG_TOKEN }}
